# OpenMHC Quickstart

End-to-end walkthrough of the public evaluation API:

1. Download the tiny dataset
2. Track 2 — define a trivial `Imputer` and run `evaluate_imputation`
3. Track 1 — define a trivial `Encoder` and run `evaluate_prediction`
4. Track 3 — define a trivial `Forecaster` and run `evaluate_forecasting`
5. Generate a paste-ready submission body

This notebook is the smallest end-to-end loop. It runs on CPU and finishes in a few minutes against the tiny version.

## 1. Install + download the dataset

If you haven't already:

```bash
pip install -e ..
```

Then download the XS dataset (~TBD MB).

In [1]:
import os
from pathlib import Path

import openmhc

# Pick a destination, or set MHC_DATA_DIR before running this cell.
DATA_ROOT = Path(os.environ.get("MHC_DATA_DIR", "~/.cache/openmhc/data-xs")).expanduser()

# Download only if not already present; otherwise reuse the cached copy.
if not (DATA_ROOT / "dataset_version.json").exists():
    openmhc.download_dataset(version="xs", dest=DATA_ROOT)

# Make this the dataset root for every subsequent openmhc.* call.
os.environ["MHC_DATA_DIR"] = str(DATA_ROOT)
print(f"dataset is at: {DATA_ROOT}")

dataset is at: /home/narayanschuetz/.cache/openmhc/data-xs

## 2. Define a trivial Imputer

Models implement the `Imputer` protocol — one method, no inheritance:
- `impute(data, observed_mask, target_mask)` — fill in artificially-masked positions

All setup (loading checkpoints, computing statistics from the training split, building per-user state) happens in `__init__`; the benchmark harness does not call any preparation method. Below we compute the per-channel global mean once from the train split via `openmhc.iter_train_data(version=VERSION)`, then use it as the fill value.

`VERSION` is set once and threaded through every public-API call. There is no auto-detection: the dataset root carries a `dataset_version.json` marker and the resolver insists the version you pass matches it.

In [2]:
import numpy as np
import openmhc

# Match what was downloaded above. Switch to "full" once you have the full release.
VERSION = "xs"


class MeanImputer:
    """Predict the channel-wise mean for every masked position."""

    def __init__(self):
        # Compute per-channel mean from the official train split.
        data_sum = np.zeros(19, dtype=np.float64)
        data_count = np.zeros(19, dtype=np.float64)
        for data, mask in openmhc.iter_train_data(version=VERSION):
            obs = (mask > 0.5) & np.isfinite(data)
            data_sum += np.where(obs, data, 0.0).sum(axis=(0, 2))
            data_count += obs.sum(axis=(0, 2))
        self.means = (data_sum / np.maximum(data_count, 1)).astype(np.float32)

    def impute(
        self,
        data: np.ndarray,
        observed_mask: np.ndarray,
        target_mask: np.ndarray,
    ) -> np.ndarray:
        out = data.copy()
        for ch in range(19):
            target = target_mask[:, ch, :] == 1
            out[:, ch, :][target] = self.means[ch]
        return out.astype(np.float32)

## 3. Run imputation evaluation

`evaluate_imputation` runs your imputer against all 6 masking scenarios (random noise, temporal slices, sleep gaps, etc.) on the test split.

In [3]:
results = openmhc.evaluate_imputation(MeanImputer(), version=VERSION)
results.summary()

Loading dataset from disk:   0%|          | 0/31 [00:00<?, ?it/s]

Filter (num_proc=1): 100%|##########| 136978/136978 [00:00<?, ? examples/s]

Filter (num_proc=1): 100%|##########| 56587/56587 [00:00<?, ? examples/s]

Loading dataset from disk:   0%|          | 0/31 [00:00<?, ?it/s]

Filter (num_proc=1): 100%|##########| 136978/136978 [00:00<?, ? examples/s]

Filter (num_proc=1): 100%|##########| 56587/56587 [00:00<?, ? examples/s]

metric,scenario,split,channel_group,macro_balanced_accuracy,macro_roc_auc,mean_normalized_mae,mean_normalized_mse,mean_normalized_rmse,n_channels
0,intensity_failure,test,binary,NaN,NaN,NaN,NaN,NaN,0
1,intensity_failure,test,continuous,NaN,NaN,6.279649,48.10646,6.821735,2
2,intensity_failure,val,binary,NaN,NaN,NaN,NaN,NaN,0
3,intensity_failure,val,continuous,NaN,NaN,5.48789,34.868949,5.895446,2
4,random_noise,test,binary,0.5,0.5,NaN,NaN,NaN,12
5,random_noise,test,continuous,NaN,NaN,0.475102,1.070293,1.030996,7
6,random_noise,val,binary,0.5,0.5,NaN,NaN,NaN,9
7,random_noise,val,continuous,NaN,NaN,0.454351,0.856238,0.914558,7
8,signal_slice,test,binary,0.5,0.5,NaN,NaN,NaN,12
9,signal_slice,test,continuous,NaN,NaN,0.476324,1.072474,1.03175,7
10,signal_slice,val,binary,0.5,0.5,NaN,NaN,NaN,8
11,signal_slice,val,continuous,NaN,NaN,0.455663,0.837408,0.903681,7
12,sleep_gap,test,binary,0.5,0.5,NaN,NaN,NaN,9
13,sleep_gap,test,continuous,NaN,NaN,0.342817,0.268312,0.499899,7
14,sleep_gap,val,binary,0.5,0.5,NaN,NaN,NaN,2
15,sleep_gap,val,continuous,NaN,NaN,0.32721,0.182835,0.371171,7
16,temporal_slice,test,binary,0.5,0.5,NaN,NaN,NaN,12
17,temporal_slice,test,continuous,NaN,NaN,0.473795,1.0448,1.01899,7
18,temporal_slice,val,binary,0.5,0.5,NaN,NaN,NaN,8
19,temporal_slice,val,continuous,NaN,NaN,0.452157,0.822686,0.895622,7
20,workout_gap,test,binary,NaN,NaN,NaN,NaN,NaN,0
21,workout_gap,test,continuous,NaN,NaN,2.260235,9.003078,2.844498,2
22,workout_gap,val,binary,NaN,NaN,NaN,NaN,NaN,0
23,workout_gap,val,continuous,NaN,NaN,2.44923,10.552987,3.130795,2

## 4. Define a trivial Encoder

For Track 1 (outcome prediction) the protocol is just `encode(weekly_tensors) -> embeddings`. Here we mean-pool over the time axis.

In [4]:
class MeanPoolEncoder:
    """Average over the 168 hours, take the 19 sensor channels."""

    def encode(self, weekly_tensors: np.ndarray) -> np.ndarray:
        # weekly_tensors: (B, 168, 38). Cols 0-18 sensors, 19-37 missingness.
        return weekly_tensors[:, :, :19].mean(axis=1).astype(np.float32)

## 5. Run prediction evaluation (Track 1)

`evaluate_prediction` extracts your embeddings, then fits a linear probe per task (logistic regression for binary, ordinal logistic for ordinal, ridge regression for continuous).

In [5]:
# tasks="all" is fine on the XS dataset; restrict if you want a faster loop
results = openmhc.evaluate_prediction(
    MeanPoolEncoder(), version=VERSION, tasks=["BiologicalSex", "age"]
)
results.summary()

Encoding:   0%|          | 0/112 [00:00<?, ?batch/s]

Encoding:   1%|          | 1/112 [00:00<00:34,  3.25batch/s]

Encoding:   2%|▏         | 2/112 [00:00<00:32,  3.40batch/s]

Encoding:   3%|▎         | 3/112 [00:00<00:31,  3.42batch/s]

Encoding:   4%|▎         | 4/112 [00:01<00:30,  3.50batch/s]

Encoding:   4%|▍         | 5/112 [00:01<00:30,  3.54batch/s]

Encoding:   5%|▌         | 6/112 [00:01<00:30,  3.45batch/s]

Encoding:   6%|▋         | 7/112 [00:02<00:30,  3.40batch/s]

Encoding:   7%|▋         | 8/112 [00:02<00:30,  3.39batch/s]

Encoding:   8%|▊         | 9/112 [00:02<00:29,  3.46batch/s]

Encoding:   9%|▉         | 10/112 [00:02<00:29,  3.45batch/s]

Encoding:  10%|▉         | 11/112 [00:03<00:29,  3.39batch/s]

Encoding:  11%|█         | 12/112 [00:03<00:29,  3.41batch/s]

Encoding:  12%|█▏        | 13/112 [00:03<00:28,  3.44batch/s]

Encoding:  12%|█▎        | 14/112 [00:04<00:28,  3.39batch/s]

Encoding:  13%|█▎        | 15/112 [00:04<00:29,  3.32batch/s]

Encoding:  14%|█▍        | 16/112 [00:04<00:29,  3.28batch/s]

Encoding:  15%|█▌        | 17/112 [00:05<00:29,  3.21batch/s]

Encoding:  16%|█▌        | 18/112 [00:05<00:29,  3.18batch/s]

Encoding:  17%|█▋        | 19/112 [00:05<00:29,  3.18batch/s]

Encoding:  18%|█▊        | 20/112 [00:06<00:29,  3.10batch/s]

Encoding:  19%|█▉        | 21/112 [00:06<00:29,  3.12batch/s]

Encoding:  20%|█▉        | 22/112 [00:06<00:27,  3.22batch/s]

Encoding:  21%|██        | 23/112 [00:06<00:27,  3.30batch/s]

Encoding:  21%|██▏       | 24/112 [00:07<00:26,  3.35batch/s]

Encoding:  22%|██▏       | 25/112 [00:07<00:26,  3.26batch/s]

Encoding:  23%|██▎       | 26/112 [00:07<00:26,  3.22batch/s]

Encoding:  24%|██▍       | 27/112 [00:08<00:27,  3.10batch/s]

Encoding:  25%|██▌       | 28/112 [00:08<00:26,  3.11batch/s]

Encoding:  26%|██▌       | 29/112 [00:08<00:26,  3.12batch/s]

Encoding:  27%|██▋       | 30/112 [00:09<00:25,  3.18batch/s]

Encoding:  28%|██▊       | 31/112 [00:09<00:25,  3.18batch/s]

Encoding:  29%|██▊       | 32/112 [00:09<00:25,  3.15batch/s]

Encoding:  29%|██▉       | 33/112 [00:10<00:25,  3.05batch/s]

Encoding:  30%|███       | 34/112 [00:10<00:27,  2.87batch/s]

Encoding:  31%|███▏      | 35/112 [00:10<00:26,  2.94batch/s]

Encoding:  32%|███▏      | 36/112 [00:11<00:25,  2.94batch/s]

Encoding:  33%|███▎      | 37/112 [00:11<00:28,  2.67batch/s]

Encoding:  34%|███▍      | 38/112 [00:12<00:27,  2.65batch/s]

Encoding:  35%|███▍      | 39/112 [00:12<00:27,  2.65batch/s]

Encoding:  36%|███▌      | 40/112 [00:12<00:25,  2.78batch/s]

Encoding:  37%|███▋      | 41/112 [00:13<00:24,  2.94batch/s]

Encoding:  38%|███▊      | 42/112 [00:13<00:22,  3.09batch/s]

Encoding:  38%|███▊      | 43/112 [00:13<00:21,  3.19batch/s]

Encoding:  39%|███▉      | 44/112 [00:13<00:20,  3.26batch/s]

Encoding:  40%|████      | 45/112 [00:14<00:19,  3.35batch/s]

Encoding:  41%|████      | 46/112 [00:14<00:19,  3.35batch/s]

Encoding:  42%|████▏     | 47/112 [00:14<00:19,  3.40batch/s]

Encoding:  43%|████▎     | 48/112 [00:15<00:18,  3.43batch/s]

Encoding:  44%|████▍     | 49/112 [00:15<00:18,  3.45batch/s]

Encoding:  45%|████▍     | 50/112 [00:15<00:18,  3.43batch/s]

Encoding:  46%|████▌     | 51/112 [00:15<00:18,  3.33batch/s]

Encoding:  46%|████▋     | 52/112 [00:16<00:18,  3.27batch/s]

Encoding:  47%|████▋     | 53/112 [00:16<00:18,  3.20batch/s]

Encoding:  48%|████▊     | 54/112 [00:16<00:18,  3.14batch/s]

Encoding:  49%|████▉     | 55/112 [00:17<00:17,  3.23batch/s]

Encoding:  50%|█████     | 56/112 [00:17<00:17,  3.29batch/s]

Encoding:  51%|█████     | 57/112 [00:17<00:16,  3.36batch/s]

Encoding:  52%|█████▏    | 58/112 [00:18<00:16,  3.35batch/s]

Encoding:  53%|█████▎    | 59/112 [00:18<00:16,  3.27batch/s]

Encoding:  54%|█████▎    | 60/112 [00:18<00:16,  3.22batch/s]

Encoding:  54%|█████▍    | 61/112 [00:19<00:15,  3.19batch/s]

Encoding:  55%|█████▌    | 62/112 [00:19<00:15,  3.21batch/s]

Encoding:  56%|█████▋    | 63/112 [00:19<00:15,  3.24batch/s]

Encoding:  57%|█████▋    | 64/112 [00:19<00:15,  3.19batch/s]

Encoding:  58%|█████▊    | 65/112 [00:20<00:15,  3.08batch/s]

Encoding:  59%|█████▉    | 66/112 [00:20<00:14,  3.21batch/s]

Encoding:  60%|█████▉    | 67/112 [00:20<00:14,  3.15batch/s]

Encoding:  61%|██████    | 68/112 [00:21<00:13,  3.18batch/s]

Encoding:  62%|██████▏   | 69/112 [00:21<00:13,  3.28batch/s]

Encoding:  62%|██████▎   | 70/112 [00:21<00:12,  3.29batch/s]

Encoding:  63%|██████▎   | 71/112 [00:22<00:12,  3.26batch/s]

Encoding:  64%|██████▍   | 72/112 [00:22<00:12,  3.23batch/s]

Encoding:  65%|██████▌   | 73/112 [00:22<00:11,  3.25batch/s]

Encoding:  66%|██████▌   | 74/112 [00:23<00:11,  3.31batch/s]

Encoding:  67%|██████▋   | 75/112 [00:23<00:10,  3.42batch/s]

Encoding:  68%|██████▊   | 76/112 [00:23<00:10,  3.42batch/s]

Encoding:  69%|██████▉   | 77/112 [00:23<00:10,  3.48batch/s]

Encoding:  70%|██████▉   | 78/112 [00:24<00:09,  3.46batch/s]

Encoding:  71%|███████   | 79/112 [00:24<00:09,  3.36batch/s]

Encoding:  71%|███████▏  | 80/112 [00:24<00:09,  3.34batch/s]

Encoding:  72%|███████▏  | 81/112 [00:25<00:09,  3.28batch/s]

Encoding:  73%|███████▎  | 82/112 [00:25<00:09,  3.29batch/s]

Encoding:  74%|███████▍  | 83/112 [00:25<00:08,  3.29batch/s]

Encoding:  75%|███████▌  | 84/112 [00:26<00:08,  3.30batch/s]

Encoding:  76%|███████▌  | 85/112 [00:26<00:07,  3.38batch/s]

Encoding:  77%|███████▋  | 86/112 [00:26<00:07,  3.44batch/s]

Encoding:  78%|███████▊  | 87/112 [00:26<00:07,  3.48batch/s]

Encoding:  79%|███████▊  | 88/112 [00:27<00:06,  3.46batch/s]

Encoding:  79%|███████▉  | 89/112 [00:27<00:06,  3.34batch/s]

Encoding:  80%|████████  | 90/112 [00:27<00:06,  3.32batch/s]

Encoding:  81%|████████▏ | 91/112 [00:28<00:06,  3.33batch/s]

Encoding:  82%|████████▏ | 92/112 [00:28<00:06,  3.29batch/s]

Encoding:  83%|████████▎ | 93/112 [00:28<00:05,  3.25batch/s]

Encoding:  84%|████████▍ | 94/112 [00:28<00:05,  3.30batch/s]

Encoding:  85%|████████▍ | 95/112 [00:29<00:05,  3.29batch/s]

Encoding:  86%|████████▌ | 96/112 [00:29<00:04,  3.31batch/s]

Encoding:  87%|████████▋ | 97/112 [00:29<00:04,  3.28batch/s]

Encoding:  88%|████████▊ | 98/112 [00:30<00:04,  3.29batch/s]

Encoding:  88%|████████▊ | 99/112 [00:30<00:03,  3.28batch/s]

Encoding:  89%|████████▉ | 100/112 [00:30<00:03,  3.27batch/s]

Encoding:  90%|█████████ | 101/112 [00:31<00:03,  3.32batch/s]

Encoding:  91%|█████████ | 102/112 [00:31<00:03,  3.29batch/s]

Encoding:  92%|█████████▏| 103/112 [00:31<00:02,  3.44batch/s]

Encoding:  93%|█████████▎| 104/112 [00:31<00:02,  3.42batch/s]

Encoding:  94%|█████████▍| 105/112 [00:32<00:02,  3.42batch/s]

Encoding:  95%|█████████▍| 106/112 [00:32<00:01,  3.34batch/s]

Encoding:  96%|█████████▌| 107/112 [00:32<00:01,  3.29batch/s]

Encoding:  96%|█████████▋| 108/112 [00:33<00:01,  3.35batch/s]

Encoding:  97%|█████████▋| 109/112 [00:33<00:00,  3.25batch/s]

Encoding:  98%|█████████▊| 110/112 [00:33<00:00,  3.21batch/s]

Encoding:  99%|█████████▉| 111/112 [00:34<00:00,  3.24batch/s]

Encoding: 100%|██████████| 112/112 [00:34<00:00,  3.28batch/s]

/home/narayanschuetz/myheartcounts-dataset/src/openmhc/_evaluate.py:483: UserWarning: Predictions are constant (zero variance). Pearson correlation will be NaN.
  m = compute_regression_metrics(y_test, test_pred)

metric,task,task_type,auprc,auroc,mae,mse,r2
0,BiologicalSex,binary,0.694444,0.5,NaN,NaN,NaN
1,age,regression,NaN,NaN,11.872222,202.545556,-0.001557

## 7. Generate a leaderboard submission

`results.to_submission_yaml(...)` produces a paste-ready body matching the textareas in the [submission issue template](https://github.com/AshleyLab/myheartcounts-dataset/issues/new?template=submission.yml).

For Track 2 imputation, skill scores and per-category subgroup scores are computed locally against the frozen LOCF baseline (`data/baselines/imputation_locf.json`). For Track 1 and Track 3, those fields are emitted as `—` and filled in by the maintainers from `raw_metrics` during ingestion.

In [6]:
class LastValueForecaster:
    """Repeat the most recent observed value across the forecast horizon."""

    def predict(self, history: np.ndarray, horizon: int) -> np.ndarray:
        # history: (n_channels, history_length); returns (n_channels, horizon)
        last = np.nan_to_num(history[:, -1:], nan=0.0)
        return np.tile(last, (1, horizon)).astype(np.float32)


# max_samples keeps this fast on the tiny dataset; remove for full eval
forecast_results = openmhc.evaluate_forecasting(
    LastValueForecaster(), version=VERSION, forecasting_length=24, max_samples=20
)
forecast_results.summary()

████████╗██╗███╗   ███╗███████╗    ███████╗███████╗██████╗ ██╗███████╗███████╗    █████╗ ██╗
╚══██╔══╝██║████╗ ████║██╔════╝    ██╔════╝██╔════╝██╔══██╗██║██╔════╝██╔════╝   ██╔══██╗██║
   ██║   ██║██╔████╔██║█████╗█████╗███████╗█████╗  ██████╔╝██║█████╗  ███████╗   ███████║██║
   ██║   ██║██║╚██╔╝██║██╔══╝╚════╝╚════██║██╔══╝  ██╔══██╗██║██╔══╝  ╚════██║   ██╔══██║██║
   ██║   ██║██║ ╚═╝ ██║███████╗    ███████║███████╗██║  ██║██║███████╗███████║██╗██║  ██║██║
   ╚═╝   ╚═╝╚═╝     ╚═╝╚══════╝    ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚═╝╚═╝  ╚═╝╚═╝
ai4ts v0.0.3 - building AI for unified time-series analysis, https://time-series.ai


================================================================================

                      FORECASTING EVALUATION CONFIGURATION

================================================================================

┌─ Seed                 42

│

├─ Experiment Name      "openmhc_run"

│

├─ Debug Mode           False

│

├─ Time Granularity     "hourly"

│

├─ Data

│  • Trajectory Hf Dir    "/home/narayanschuetz/.cache/openmhc/data-xs/hourly_trajectory"

│  • Task Name            "hourly_trajectory_forecasting"

│  • Split File           "/home/narayanschuetz/.cache/openmhc/data-xs/splits/sharable_users_seed42_2026_xs.json"

│  • Day Remain Mask      "/home/narayanschuetz/.cache/openmhc/data-xs/forecasting_sample_index/day_remain_mask.json"

│  • Sample Index File    "/home/narayanschuetz/.cache/openmhc/data-xs/forecasting_sample_index/sample_index_P_24_raw.json"

│  • Train Ratio          0.8

│  • Val Ratio            0.1

│  • Split Seed           42

│  • Num Workers          4

│  • Max Samples          20

│

├─ Forecasting

│  • Forecasting Length   24

│  • Daily Start Hour Offset 0

│

├─ Model

│  • Type                 "seasonal_naive"

│  • Name                 None

│  • Seasonal Naive:
  - Season Length: 24
  - Quantile Levels: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

│  • Seasonal Naive Average History:
  - Season Length: 24

│  • Autoarima:
  - Start P: 2
  - Start Q: 2
  - Max P: 5
  - Max Q: 5
  - Seasonal: True
  - Start P: 1
  - Start Q: 1
  - Max P: 2
  - Max Q: 2
  - Max D: 2
  - Max D: 1
  - Information Criterion: "aic"
  - Suppress Warnings: True
  - Trace: False
  - Error Action: "ignore"
  - Stepwise: False
  - N Jobs: -1
  - Max History Length: 336

│  • Autoets:
  - Auto: True
  - Sp: 24
  - Information Criterion: "aic"
  - N Jobs: -1
  - Max History Length: 336

│  • Chronos2:
  - Temp: 1
  - Pretrained Model Name Or Path: "amazon/chronos-2"
  - Checkpoint Path: None
  - Training Output Dir: None
  - Finetuned Ckpt Name: None
  - Device: "cuda"
  - Torch Dtype: "auto"

│  • Toto:
  - Pretrained Model Name Or Path: "Datadog/Toto-Open-Base-1.0"
  - Checkpoint Path: None
  - Lora Alpha: None
  - Device: "cuda"
  - Context Length: 2048
  - Num Samples: 256
  - Samples Per Batch: 256
  - Use Kv Cache: True
  - Time Interval Seconds: 3600

│  • Mixlinear:
  - Checkpoint Path: None
  - Device: "cuda"
  - Batch Size: 64
  - N Steps: None
  - N Pred Steps: None
  - N Features: None
  - Period Len: 24
  - Lpf: 2
  - Alpha: 0.5
  - Rank: 2

│  • Dlinear:
  - Checkpoint Path: None
  - Device: "cuda"
  - Batch Size: 64
  - N Steps: None
  - N Pred Steps: None
  - N Features: None
  - Moving Avg Window Size: 25
  - Individual: False
  - D Model: None

│  • Segrnn:
  - Checkpoint Path: None
  - Device: "cuda"
  - Batch Size: 64
  - N Steps: None
  - N Pred Steps: None
  - N Features: None
  - Seg Len: 24
  - D Model: 64
  - Dropout: 0.1

│

├─ Features

│  • Covariate Types      None

│  • Channel              "all"

│

├─ Evaluator

│  • Mode                 "sequential"

│

└─ Output

│  • Results Dir          "/var/tmp/openmhc-fc-yizi_snh"

│  • Save Config          True

│  • Overwrite Existing Parquet False

================================================================================

/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/evaluation/quantiles_metrics.py:182: RuntimeWarning: Mean of empty slice
  ql_by_feature[var_name] = float(np.nanmean(ql))

/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")

/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")

/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")

/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")

/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")

/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")

/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")
/home/narayanschuetz/myheartcounts-dataset/src/forecasting_evaluation/runner.py:160: RuntimeWarning: Mean of empty slice
  ch_mean = float(np.nanmean(ch_arr)) if ch_arr.size else float("nan")

metric,channel,mae,mase,mase_all,mse,ql,sql
0,ch_0,172.406827,1.126707,0.843561,212979.762049,86.203413,0.563354
1,ch_1,138.726720,1.409292,0.963318,149358.500563,69.363360,0.704646
2,ch_2,0.000000,NaN,NaN,0.000000,0.000000,NaN
3,ch_3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,ch_4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,ch_5,0.145562,1.858889,1.685999,0.045959,0.072781,0.929444
6,ch_6,239.186330,1.082481,0.884697,266894.592831,119.593165,0.541240
7,ch_9,0.068182,0.727273,1.636364,0.068182,0.034091,0.363636

## 6. Generate a leaderboard submission

`results.to_submission_yaml(...)` produces a paste-ready body matching the textareas in the [submission issue template](https://github.com/AshleyLab/myheartcounts-dataset/issues/new?template=submission.yml).

For Track 2 imputation, skill scores and per-category subgroup scores are computed locally against the frozen LOCF baseline (`data/baselines/imputation_locf.json`). For Track 1, those fields are emitted as `—` and filled in by the maintainers from `raw_metrics` during ingestion.

In [7]:
imputation_results = openmhc.evaluate_imputation(MeanImputer(), version=VERSION)

submission_body = imputation_results.to_submission_yaml(
    method_name="MeanImputer (demo)",
    submitter_team="Stanford CS",
    paper_url="https://arxiv.org/abs/0000.00000",
    code_url="https://github.com/example/mean-imputer",
    method_category="Statistical / Classical baseline",
)
print(submission_body)

Loading dataset from disk:   0%|          | 0/31 [00:00<?, ?it/s]

Filter (num_proc=1): 100%|##########| 136978/136978 [00:00<?, ? examples/s]

Filter (num_proc=1): 100%|##########| 56587/56587 [00:00<?, ? examples/s]

Loading dataset from disk:   0%|          | 0/31 [00:00<?, ?it/s]

Filter (num_proc=1): 100%|##########| 136978/136978 [00:00<?, ? examples/s]

Filter (num_proc=1): 100%|##########| 56587/56587 [00:00<?, ? examples/s]

# Paste-ready submission body for: MeanImputer (demo)
# Track: Track 2 — Imputation (Daily, single-day context)
#
# Single-input fields (top of the form):
#   method_name:       MeanImputer (demo)
#   submitter_team:    Stanford CS
#   track:             Track 2 — Imputation (Daily, single-day context)
#   method_category:   Statistical / Classical baseline
#   foundation_variant: N/A (not a foundation model)
#   feature_dim:       —
#   paper_url:         https://arxiv.org/abs/0000.00000
#   code_url:          https://github.com/example/mean-imputer

# --- aggregate_metrics (textarea) ---
skill_score: -31.60
fair_skill_score: —  # computed by maintainers from subgroup runs
avg_rank: —  # computed by maintainers vs current leaderboard

# --- subgroup_metrics (textarea) ---
activity: 10.23
physiology: -5.87
sleep: -140.04
workouts: -48.09
semantic: —  # paper-only category; ignore unless reporting it explicitly

# --- raw_metrics (optional textarea) ---
{
  "random_noise": {
    "val": {
      "n_samples": 1159,
      "per_channel": {
        "ch_0": {
          "channel_idx": 0,
          "n_masked": 717780,
          "rmse": 12.329872101945009,
          "mse": 152.02574605032183,
          "mae": 5.77522708908022,
          "normalized_rmse": 0.9569906633488738,
          "normalized_mse": 0.9158311297369175,
          "normalized_mae": 0.44824782911555255,
          "per_sample_rmse_mean": 10.191917229421211,
          "per_sample_rmse_std": 7.003366819860351,
          "per_sample_mse_mean": 152.9223232269287,
          "per_sample_mse_std": 235.60845776798885,
          "per_sample_mae_mean": 5.781511987339367,
          "per_sample_mae_std": 2.8112045621890958
        },
        "ch_1": {
          "channel_idx": 1,
          "n_masked": 713790,
          "rmse": 9.022700589812219,
          "mse": 81.40912593339777,
          "mae": 4.108981983496546,
          "normalized_rmse": 0.9937044253845174,
          "normalized_mse": 0.9874484850287741,
          "normalized_mae": 0.4525378560645276,
          "per_sample_rmse_mean": 7.346991472051601,
          "per_sample_rmse_std": 5.229301267828987,
          "per_sample_mse_mean": 81.32387541315772,
          "per_sample_mse_std": 135.10514020403318,
          "per_sample_mae_mean": 4.106764225285462,
          "per_sample_mae_std": 2.157415732097976
        },
        "ch_2": {
          "channel_idx": 2,
          "n_masked": 723510,
          "rmse": 0.05197895192993376,
          "mse": 0.0027018114437343645,
          "mae": 0.005771739344048458,
          "normalized_rmse": 0.8718203917784949,
          "normalized_mse": 0.7600707955208085,
          "normalized_mae": 0.0968068779638838,
          "per_sample_rmse_mean": 0.022915546068719064,
          "per_sample_rmse_std": 0.046948280897821514,
          "per_sample_mse_mean": 0.0027292633289363434,
          "per_sample_mse_std": 0.0101541645567673,
          "per_sample_mae_mean": 0.005792439704251563,
          "per_sample_mae_std": 0.008055495946655687
        },
        "ch_3": {
          "channel_idx": 3,
          "n_masked": 657060,
          "rmse": 11.881224600447142,
          "mse": 141.16349800627034,
          "mae": 6.50097784068426,
          "normalized_rmse": 0.8249010662110574,
          "normalized_mse": 0.6804617690361392,
          "normalized_mae": 0.4513561297370881,
          "per_sample_rmse_mean": 10.291157747897541,
          "per_sample_rmse_std": 5.974193127185591,
          "per_sample_mse_mean": 141.5989110031377,
          "per_sample_mse_std": 184.175694385573,
          "per_sample_mae_mean": 6.501430513031205,
          "per_sample_mae_std": 2.2623901818134695
        },
        "ch_4": {
          "channel_idx": 4,
          "n_masked": 661470,
          "rmse": 10.218573087480703,
          "mse": 104.41923594418492,
          "mae": 5.23637579935598,
          "normalized_rmse": 0.8734417770540907,
          "normalized_mse": 0.762900537903408,
          "normalized_mae": 0.4475839575993206,
          "per_sample_rmse_mean": 8.658476054603568,
          "per_sample_rmse_std": 5.431777960500115,
          "per_sample_mse_mean": 104.47341967303554,
          "per_sample_mse_std": 161.76160060160237,
          "per_sample_mae_mean": 5.240947779426118,
          "per_sample_mae_std": 1.9779451731395257
        },
        "ch_5": {
          "channel_idx": 5,
          "n_masked": 74481,
          "rmse": 0.34472172401985,
          "mse": 0.11883306701121762,
          "mae": 0.2454744120983875,
          "normalized_rmse": 1.1831945275464997,
          "normalized_mse": 1.3999492900159842,
          "normalized_mae": 0.8425462070118382,
          "per_sample_rmse_mean": 0.27274514569447994,
          "per_sample_rmse_std": 0.15367349124651375,
          "per_sample_mse_mean": 0.09800545604940239,
          "per_sample_mse_std": 0.12996418682290325,
          "per_sample_mae_mean": 0.22620086812419318,
          "per_sample_mae_std": 0.1265705536758093
        },
        "ch_6": {
          "channel_idx": 6,
          "n_masked": 665250,
          "rmse": 699.8646635263938,
          "mse": 489810.5472529124,
          "mae": 442.6506967305524,
          "normalized_rmse": 0.6978556026702688,
          "normalized_mse": 0.48700244217828415,
          "normalized_mae": 0.44138000507531605,
          "per_sample_rmse_mean": 624.5078559352472,
          "per_sample_rmse_std": 313.7909125500725,
          "per_sample_mse_mean": 488474.798898259,
          "per_sample_mse_std": 618773.8424021722,
          "per_sample_mae_mean": 442.6320071215209,
          "per_sample_mae_std": 118.4053983701447
        },
        "ch_7": {
          "channel_idx": 7,
          "n_masked": 326675,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_8": {
          "channel_idx": 8,
          "n_masked": 334183,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_9": {
          "channel_idx": 9,
          "n_masked": 58530,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_10": {
          "channel_idx": 10,
          "n_masked": 26700,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_11": {
          "channel_idx": 11,
          "n_masked": 51600,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_12": {
          "channel_idx": 12,
          "n_masked": 52590,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_13": {
          "channel_idx": 13,
          "n_masked": 0,
          "error": "no_masked_positions"
        },
        "ch_14": {
          "channel_idx": 14,
          "n_masked": 15090,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_15": {
          "channel_idx": 15,
          "n_masked": 31500,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_16": {
          "channel_idx": 16,
          "n_masked": 0,
          "error": "no_masked_positions"
        },
        "ch_17": {
          "channel_idx": 17,
          "n_masked": 0,
          "error": "no_masked_positions"
        },
        "ch_18": {
          "channel_idx": 18,
          "n_masked": 13050,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        }
      },
      "continuous": {
        "mean_normalized_rmse": 0.9145583505705435,
        "mean_normalized_mse": 0.8562377784886165,
        "mean_normalized_mae": 0.45435126608107523,
        "n_channels": 7
      },
      "binary": {
        "macro_balanced_accuracy": 0.5,
        "n_channels": 9,
        "macro_roc_auc": 0.5
      },
      "n_applicable": 1159,
      "n_total": 1159
    },
    "test": {
      "n_samples": 22799,
      "per_channel": {
        "ch_0": {
          "channel_idx": 0,
          "n_masked": 16111170,
          "rmse": 13.817772852793183,
          "mse": 190.93084661138826,
          "mae": 6.186159912656871,
          "normalized_rmse": 1.0724750020977618,
          "normalized_mse": 1.1502026301245942,
          "normalized_mae": 0.48014263485035086,
          "per_sample_rmse_mean": 11.724187320619054,
          "per_sample_rmse_std": 7.306660756137351,
          "per_sample_mse_mean": 190.8438597009878,
          "per_sample_mse_std": 237.8803767570985,
          "per_sample_mae_mean": 6.185441021996177,
          "per_sample_mae_std": 2.901728498749262
        },
        "ch_1": {
          "channel_idx": 1,
          "n_masked": 16114500,
          "rmse": 10.24117416144422,
          "mse": 104.88164820503273,
          "mae": 4.383692264730522,
          "normalized_rmse": 1.1278995666609497,
          "normalized_mse": 1.272157432473958,
          "normalized_mae": 0.48279274698588404,
          "per_sample_rmse_mean": 8.464199989702907,
          "per_sample_rmse_std": 5.741549400074568,
          "per_sample_mse_mean": 104.60807100047367,
          "per_sample_mse_std": 148.87697468688094,
          "per_sample_mae_mean": 4.3797873302020145,
          "per_sample_mae_std": 2.2046004826249095
        },
        "ch_2": {
          "channel_idx": 2,
          "n_masked": 15418890,
          "rmse": 0.06507747317156293,
          "mse": 0.004235077514395492,
          "mae": 0.006914266237509639,
          "normalized_rmse": 1.091516201266715,
          "normalized_mse": 1.19140761762772,
          "normalized_mae": 0.11596998546973504,
          "per_sample_rmse_mean": 0.04414922972789784,
          "per_sample_rmse_std": 0.047862034532837716,
          "per_sample_mse_mean": 0.0042399288354183886,
          "per_sample_mse_std": 0.012224121199547975,
          "per_sample_mae_mean": 0.006919941541408887,
          "per_sample_mae_std": 0.007434320548802958
        },
        "ch_3": {
          "channel_idx": 3,
          "n_masked": 15586020,
          "rmse": 15.235018582708097,
          "mse": 232.10579121546104,
          "mae": 7.805989149250418,
          "normalized_rmse": 1.0577514940798456,
          "normalized_mse": 1.1188382232281457,
          "normalized_mae": 0.5419617075336056,
          "per_sample_rmse_mean": 13.470661895538505,
          "per_sample_rmse_std": 7.118939836351374,
          "per_sample_mse_mean": 232.13803631923182,
          "per_sample_mse_std": 254.63987824244242,
          "per_sample_mae_mean": 7.806827431239966,
          "per_sample_mae_std": 3.054159047399659
        },
        "ch_4": {
          "channel_idx": 4,
          "n_masked": 15310230,
          "rmse": 12.333616805966,
          "mse": 152.118103516407,
          "mae": 6.012172612690992,
          "normalized_rmse": 1.054227051887051,
          "normalized_mse": 1.111394676930463,
          "normalized_mae": 0.5138958919047485,
          "per_sample_rmse_mean": 10.700436789135653,
          "per_sample_rmse_std": 6.126083768093378,
          "per_sample_mse_mean": 152.02824981349306,
          "per_sample_mse_std": 196.53423004470199,
          "per_sample_mae_mean": 6.011483507955298,
          "per_sample_mae_std": 2.456607280026545
        },
        "ch_5": {
          "channel_idx": 5,
          "n_masked": 2629734,
          "rmse": 0.2777666134113594,
          "mse": 0.07715429152601556,
          "mae": 0.21051482773542876,
          "normalized_rmse": 0.9533833060794275,
          "normalized_mse": 0.908939728310939,
          "normalized_mae": 0.7225538014819475,
          "per_sample_rmse_mean": 0.24607374022796769,
          "per_sample_rmse_std": 0.10844889151315507,
          "per_sample_mse_mean": 0.07231344772692978,
          "per_sample_mse_std": 0.0804723165545022,
          "per_sample_mae_mean": 0.2004010485607595,
          "per_sample_mae_std": 0.08772977461577347
        },
        "ch_6": {
          "channel_idx": 6,
          "n_masked": 15313440,
          "rmse": 862.1922930548732,
          "mse": 743375.5502032202,
          "mae": 469.7455495303472,
          "normalized_rmse": 0.8597172476972448,
          "normalized_mse": 0.7391137459881256,
          "normalized_mae": 0.46839707825427923,
          "per_sample_rmse_mean": 750.6048255230685,
          "per_sample_rmse_std": 425.16664025574073,
          "per_sample_mse_mean": 744174.2760187865,
          "per_sample_mse_std": 1022148.6616216975,
          "per_sample_mae_mean": 469.80598421025365,
          "per_sample_mae_std": 171.13463165537055
        },
        "ch_7": {
          "channel_idx": 7,
          "n_masked": 7219548,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_8": {
          "channel_idx": 8,
          "n_masked": 10433510,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_9": {
          "channel_idx": 9,
          "n_masked": 6183930,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_10": {
          "channel_idx": 10,
          "n_masked": 5517900,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_11": {
          "channel_idx": 11,
          "n_masked": 5668740,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_12": {
          "channel_idx": 12,
          "n_masked": 4565400,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_13": {
          "channel_idx": 13,
          "n_masked": 813450,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_14": {
          "channel_idx": 14,
          "n_masked": 2579220,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_15": {
          "channel_idx": 15,
          "n_masked": 3947880,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_16": {
          "channel_idx": 16,
          "n_masked": 2548500,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_17": {
          "channel_idx": 17,
          "n_masked": 2307480,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_18": {
          "channel_idx": 18,
          "n_masked": 3407940,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        }
      },
      "continuous": {
        "mean_normalized_rmse": 1.0309956956812851,
        "mean_normalized_mse": 1.070293436383421,
        "mean_normalized_mae": 0.4751019780686501,
        "n_channels": 7
      },
      "binary": {
        "macro_balanced_accuracy": 0.5,
        "n_channels": 12,
        "macro_roc_auc": 0.5
      },
      "n_applicable": 22799,
      "n_total": 22799
    }
  },
  "temporal_slice": {
    "val": {
      "n_samples": 1159,
      "per_channel": {
        "ch_0": {
          "channel_idx": 0,
          "n_masked": 383730,
          "rmse": 11.899422144012961,
          "mse": 141.596247361426,
          "mae": 5.686521773121727,
          "normalized_rmse": 0.9235810231373665,
          "normalized_mse": 0.8530019062994645,
          "normalized_mae": 0.4413629110515364,
          "per_sample_rmse_mean": 9.487987907607145,
          "per_sample_rmse_std": 7.205545524086791,
          "per_sample_mse_mean": 141.94180093798974,
          "per_sample_mse_std": 248.1347469249892,
          "per_sample_mae_mean": 5.691494848631849,
          "per_sample_mae_std": 3.156851243245033
        },
        "ch_1": {
          "channel_idx": 1,
          "n_masked": 383730,
          "rmse": 8.657707020958926,
          "mse": 74.95589086076147,
          "mae": 4.027103692700597,
          "normalized_rmse": 0.9535062916887217,
          "normalized_mse": 0.9091742482899776,
          "normalized_mae": 0.44352028764396795,
          "per_sample_rmse_mean": 6.798828504543112,
          "per_sample_rmse_std": 5.399640581233929,
          "per_sample_mse_mean": 75.38018803042594,
          "per_sample_mse_std": 139.0054168316254,
          "per_sample_mae_mean": 4.03482717064896,
          "per_sample_mae_std": 2.3718047576843855
        },
        "ch_2": {
          "channel_idx": 2,
          "n_masked": 387197,
          "rmse": 0.05343799562907522,
          "mse": 0.002855619376853062,
          "mae": 0.005922177383621903,
          "normalized_rmse": 0.8962922982363648,
          "normalized_mse": 0.8033398838778246,
          "normalized_mae": 0.09933010988237465,
          "per_sample_rmse_mean": 0.022271755231384506,
          "per_sample_rmse_std": 0.048331586839229876,
          "per_sample_mse_mean": 0.0028319733302516158,
          "per_sample_mse_std": 0.012336251322107035,
          "per_sample_mae_mean": 0.005914021921232566,
          "per_sample_mae_std": 0.009234548499970052
        },
        "ch_3": {
          "channel_idx": 3,
          "n_masked": 356314,
          "rmse": 11.411610167896775,
          "mse": 130.22484662404509,
          "mae": 6.4237329995453445,
          "normalized_rmse": 0.7922962246104434,
          "normalized_mse": 0.6277333075319621,
          "normalized_mae": 0.44599310076005855,
          "per_sample_rmse_mean": 9.597853735818957,
          "per_sample_rmse_std": 6.144826405111714,
          "per_sample_mse_mean": 129.87768776346732,
          "per_sample_mse_std": 204.9592670701164,
          "per_sample_mae_mean": 6.41682942933175,
          "per_sample_mae_std": 2.6374162091806936
        },
        "ch_4": {
          "channel_idx": 4,
          "n_masked": 356314,
          "rmse": 9.675757559795164,
          "mse": 93.62028435593325,
          "mae": 5.142492646935007,
          "normalized_rmse": 0.8270441288643373,
          "normalized_mse": 0.6840019910889705,
          "normalized_mae": 0.4395592102315615,
          "per_sample_rmse_mean": 7.96574541715595,
          "per_sample_rmse_std": 5.480593328528507,
          "per_sample_mse_mean": 93.49000356921174,
          "per_sample_mse_std": 174.21675568863884,
          "per_sample_mae_mean": 5.138257199973355,
          "per_sample_mae_std": 2.2753161872275802
        },
        "ch_5": {
          "channel_idx": 5,
          "n_masked": 40243,
          "rmse": 0.3449424505920131,
          "mse": 0.11898529422042342,
          "mae": 0.24908963690113808,
          "normalized_rmse": 1.1839521313006873,
          "normalized_mse": 1.40174264921144,
          "normalized_mae": 0.8549548076436295,
          "per_sample_rmse_mean": 0.26174888423957876,
          "per_sample_rmse_std": 0.15436908296849075,
          "per_sample_mse_mean": 0.09234229233810544,
          "per_sample_mse_std": 0.13029487243124716,
          "per_sample_mae_mean": 0.22289259248099275,
          "per_sample_mae_std": 0.13298676269260476
        },
        "ch_6": {
          "channel_idx": 6,
          "n_masked": 356314,
          "rmse": 694.6758527137887,
          "mse": 482574.5403436295,
          "mae": 441.6436289340301,
          "normalized_rmse": 0.6926816870756062,
          "normalized_mse": 0.47980791960990804,
          "normalized_mae": 0.4403758282098479,
          "per_sample_rmse_mean": 599.3422705782122,
          "per_sample_rmse_std": 353.14840512579974,
          "per_sample_mse_mean": 483924.9501071137,
          "per_sample_mse_std": 817331.438418277,
          "per_sample_mae_mean": 441.66230405323915,
          "per_sample_mae_std": 157.85269425755607
        },
        "ch_7": {
          "channel_idx": 7,
          "n_masked": 176396,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_8": {
          "channel_idx": 8,
          "n_masked": 178201,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_9": {
          "channel_idx": 9,
          "n_masked": 31938,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_10": {
          "channel_idx": 10,
          "n_masked": 14526,
          "balanced_accuracy": 0.5,
          "roc_auc": 0.5
        },
        "ch_11": {
          "channel_idx": 11,

Once you have a body that looks right:

1. Open a [submission issue](https://github.com/AshleyLab/myheartcounts-dataset/issues/new?template=submission.yml).
2. Fill in the single-input fields (method name, paper URL, …) and paste the three textarea blocks above.
3. The HuggingFace Space ingests merged submissions and the public leaderboard at `https://myheartcounts.stanford.edu/benchmark` rebuilds automatically.

Submissions must follow the standard protocol — same split file, masking config, label-validity criterion as the paper. The submission template enforces required fields.